### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by najibullahjafari** [MasumaJaffery/Catalog_of_My_Things#38]
Here:

- Our kanban board project [link](https://github.com/MasumaJaffery/Catalog_of_My_Things/projects/1).
- We are four people in this project.
1.  Team member #1 is @MasumaJaffery 
2. Team member #2 is @cancelei 
3. Team member #3 is @Grandi0z 
4. Team member #4 is @najibullahjafari

**Comment by iambenkis** [comment]
#### Hi Team 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️ Tasks have descriptions
✔️ Tasks have time in the [Xpt] form
✔️ Required tasks are presents

## Suggested changes

- [ ] Good job setting up your Kanban board, everything looks great. indeed very great 👏 👏 , however, the time repartition is not fair because @najibullahjafari has [23pt] of time while @MasumaJaffery has [16pt] which is significantly lower than the [23pt], (difference >= 5 points more or less points than others) , KIndly fix that and ask again for review 👍 
 
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by najibullahjafari** [comment]
The requested change done!

**Comment by ghost** [comment]
Hi Team, 

You can go ahead with your project
Congratulations! 🎉 





## Highlights

✅ Tasks are fairly assigned
✅ Tasks have proper descriptions 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
